env:
  browser: true
  es6: true
  amd: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'preact'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true # needed for eslint-plugin-react
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - prettier
rules: {}
