name: BundleWatch

# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#configuring-workflow-events
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          # This uses the same name as the build-action so we can share the caches.
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      # - uses: jackyef/bundlewatch-gh-action@master
      # - uses: jackyef/bundlewatch-gh-action@0.0.6
      # with:
      # build-script: npm run build --if-present
      # build-script: "build"
      # bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

      # bundlewatch-2:
      # runs-on: ubuntu-latest
      # steps:
      # - uses: actions/checkout@v2
      # - run: npm ci
      - run: npm run build
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
