name: BundleStats
# https://github.com/marketplace/actions/bundlestats

on:
  pull_request: 
    types: [synchronize, opened]

jobs:
  build:
    steps:
    - name: Run bundle-stats
      uses: vio/bundle-stats-action@v1
      with:
        webpack-stats-path: 'static/stats.json'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
