name: 'Create PR'
# https://github.com/thomaseizinger/create-pull-request

on:
  create:
    branches:
      - '**'

jobs:
  create-pr-on-push:
    if: |
      contains(github.ref, 'einSelbst') == false &&
      contains(github.ref, 'dependabot') == false &&
      contains(github.ref, 'renovate') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: master
          title: ${{ steps.extract_branch.outputs.branch }}
