# This is a basic workflow to help you get started with Actions

name: linter/tinovayatkin

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ESlint Runner Action
        # https://github.com/marketplace/actions/eslint-runner-action
        # You may pin to the exact commit or the version.
        # uses: tinovyatkin/action-eslint@3d7db709c05548b9146ea96dcc7ee8a0d5b6ed75
        uses: tinovyatkin/action-eslint@v1
        with:
          # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # This check name to post annotations
          check-name: eslint-runner-action
