# This is a basic workflow to help you get started with Actions

name: linter/iCrawl

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Install eslint
        run: |
          npm ci
          npm i --save react@npm:@preact/compat react-dom@npm:@preact/compat
          npm i -g eslint
          npm i --save eslint-plugin-react@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest eslint@latest

      - name: ESLint (JS/TS) Action
        # https://github.com/marketplace/actions/eslint-js-ts-action
        # You may pin to the exact commit or the version.
        # uses: iCrawl/action-eslint@ff2a58dcbc1aaec51815d58e8bf70962c4f2b557
        uses: iCrawl/action-eslint@v1
        with:
          # Custom glob to overwrite which files to lint.
          custom-glob: # optional, default is src
