# This is a basic workflow to help you get started with Actions

name: linter/reviewdog

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run eslint with reviewdog
        # https://github.com/marketplace/actions/run-eslint-with-reviewdog
        # You may pin to the exact commit or the version.
        # uses: reviewdog/action-eslint@c93d1f8efe07ce3b9b2d186ceaa5cd6ced717633
        uses: reviewdog/action-eslint@v1.0.0
        with:
          # GITHUB_TOKEN.
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Report level for reviewdog [info,warning,error]
          level: # optional, default is error
          # Reporter of reviewdog command [github-pr-check,github-pr-review].

          reporter: # optional, default is github-pr-check
          # flags and args of eslint command. Default: '.'
          eslint_flags: # optional, default is .
