# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: ESLint (JS/TS) Action
        # https://github.com/marketplace/actions/eslint-js-ts-action
        # You may pin to the exact commit or the version.
        # uses: iCrawl/action-eslint@ff2a58dcbc1aaec51815d58e8bf70962c4f2b557
        uses: iCrawl/action-eslint@v1
        with:
          # Custom glob to overwrite which files to lint.
          custom-glob: # optional, default is src
          
      - name: Run eslint with reviewdog
        # https://github.com/marketplace/actions/run-eslint-with-reviewdog
  # You may pin to the exact commit or the version.
  # uses: reviewdog/action-eslint@c93d1f8efe07ce3b9b2d186ceaa5cd6ced717633
  uses: reviewdog/action-eslint@v1.0.0
  with:
    # GITHUB_TOKEN.
    github_token: 
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is error
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
Default is github-pr-check.
github-pr-review can use Markdown and add a link to rule page in reviewdog reports.

    reporter: # optional, default is github-pr-check
    # flags and args of eslint command. Default: '.'
    eslint_flags: # optional, default is .
    
    - name: ESlint Runner Action
      # https://github.com/marketplace/actions/eslint-runner-action
  # You may pin to the exact commit or the version.
  # uses: tinovyatkin/action-eslint@3d7db709c05548b9146ea96dcc7ee8a0d5b6ed75
  uses: tinovyatkin/action-eslint@v1
  with:
    # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # This check name to post annotations
    check-name: eslint-runner-action
