name: Lighthouse CI
# https://github.com/GoogleChrome/lighthouse-ci

on: [push]

env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: bahmutov/npm-install@v1
      - name: npm install lighthouse, build
        run: |
          npm install -g @lhci/cli@0.6.x
          npm run build
      - name: run Lighthouse CI
        run: lhci autorun
