name: Generate Pull Request Stats

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  stats:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: ./.github/actions/next-stats-action
      # - uses: vercel/next-stats-action@master
