name: Linting/eslint-prettier

on: [push]

jobs:
  build:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      # Cache deps
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install your dependencies
      - run: |
          npm i -g prettier
          npm ci

      # Run ESLint
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx

      # Run Prettier
      - run: npm run format

      - run: git status

      # commit any changed files
      # https://github.com/mikeal/publish-to-github-action
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
